runtime: python38

#B1: 384MB/600MHz/manual_scaling: More cost-effective for our application
instance_class: B1
basic_scaling:
  max_instances: 2
  idle_timeout: 3m

#F1: 384MB/600MHz/automatic_scaling
#instance_class: F1
#automatic_scaling:
#  max_instances: 2
#  min_instances: 0
#  max_idle_instances: 1
#  min_idle_instances: 0

app_engine_apis: true
entrypoint: gunicorn -b :$PORT -w 1 main:app

inbound_services:
- mail
- mail_bounce

handlers:
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/x-icon

- url: /static
  static_dir: static
  application_readable: true

- url: /images
  static_dir: images
  application_readable: true

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
