
services:
  kindleear:
    container_name: kindleear
    image: kindleear/kindleear
    restart: always
    volumes:
      - ./data/:/data/
    expose:
      - "8000"
    networks:
      - web_network
    environment:
       APP_ID: kindleear
       APP_DOMAIN: https://kindleear.appspot.com
       LOG_LEVEL: warning
       
  nginx:
    container_name: nginx
    image: nginx:stable-alpine3.17-slim
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - kindleear
    networks:
      - web_network

  # mailglove:
  #   container_name: mailglove
  #   image: thingless/mailglove
  #   restart: unless-stopped
  #   ports:
  #     - "25:25"
  #   depends_on:
  #     - kindleear
  #     - nginx
  #   environment:
  #     #change DOMAIN to your email domain
  #     DOMAIN: local
  #     URL: http://kindleear:8000/mailglove
  #   networks:
  #     - web_network

networks:
  web_network:
    driver: bridge
